name: AutoCheckin

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    branches: 
      - master
  schedule:
    - cron: "16 16 * * *" # 北京时间0:16触发
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python # 安装python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'
    - name: Set up Node.js # 安装Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install requirements # 安装轮子
      run: |
        pip install -r requirements.txt
    - name: Print current time # 输出当前时间，帮助调试
      run: date
    - name: Run script
      run: |
        python3 main.py "${{ secrets.cookie }}" "${{ secrets.teleid }}" "${{ secrets.teletoken }}" "${{ secrets.SCKEY }}" "${{ secrets.QQKEY }}" "${{ secrets.PPKEY }}"
