name: AutoCheckin

on: 
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  schedule:
    - cron: "0 17 * * *"
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python # 安装 Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install requirements # 安装依赖
      run: |
        pip install -r requirements.txt
    - name: Run script
      run: |
        python3 main.py "${{ secrets.cookie }}" "${{ secrets.teleid }}" "${{ secrets.teletoken }}" "${{ secrets.SCKEY }}" "${{ secrets.QQKEY }}" "${{ secrets.PPKEY }}"
